### ISSUE TITLE
Can nocode be licensed under MIT License?

### ISSUE THREAD

**Issue by trivikr** [kelseyhightower/nocode#137]
It's shorter, simpler, less-restrictive than Apache 2.0

**Comment by petermbenjamin** [comment]
If we've learned anything from React's licensing shenanigans is that having licenses is bad. 
*No License* seems fitting here.

**Comment by asciifaceman** [comment]
I recommend the implementation of an `UNLICENSED.md` file.

**Comment by trivikr** [comment]
How about [WTFPL](http://www.wtfpl.net/)?
Looks like it has also been requested in the past #94

**Comment by akashmishra23** [comment]
How about NoLicense.md

**Comment by asciifaceman** [comment]
Isn't any license the implementation of esoteric legal code?

**Comment by MarHoff** [comment]
Guy this is serious I just had a confirmation of prior art evidence on another issue I opened
#208 (Not sure if you can deploy nocode to yesterday)

I think it would be higly advisable to switch project to nolicence as you are already starting to suggest.
Here's a draft I'm suggesting.

```

```

**Comment by racerpeter** [comment]
May I suggest NCL-1.0? https://github.com/kelseyhightower/nocode/pull/335

**Comment by petermbenjamin** [comment]
@MarHoff - someone wrote a blog article about how *NoLicense* puts you in more risk of legal battle.

**Comment by MarHoff** [comment]
@petermbenjamin I really don’t no if old schemes applied to nocode seems like the most groundbreaking revolution since blockchain.

Unlike other solution nocode is offline self-repairing, self-deleting in case of security breach and consistently non existing event in when scaling up.

Nolicence text at all should then be more appropriate to handle no risk at all that come with implementing Nothing. Contrary to traditional licence the sole present of any text in the licence file seems to exponentially increase the risk of semantic misunderstanding of the licence text.

I grant you however that some confusion can arise for developers that come from a loosely typed language and might eventually confuse an empty string with nil or null.

**Comment by westonal** [comment]
This is a big concern to me, now I've seen this repo, are all my future works are now bound by the terms of the current license as derivative works?
