### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by drawcard** [kelseyhightower/nocode#1893]
Hi, I own a Macbook Pro and was wondering if nocode runs on High Sierra.

**Comment by azjezz** [comment]
it should run
try this 
```

```

**Comment by drawcard** [comment]
Ok yep I found the binaries in brew, I had to run:

```
brew install      
```

**Comment by bvanvliet** [comment]
Misread the issue title. However, since I'm already here: 
NoCode **`[versions` &nbsp; `.`  &nbsp; `.`  &nbsp; `-` &nbsp; `.`  &nbsp; `.`  &nbsp;`]`** successfully tested on:
- Big Mac® **`[v120.3.55b & up]`**
- Kraft™ Mac & Cheese **`[v1.0]³`**



`³` _original cheddar cheese & elbow macaroni **only**_

**Comment by omerfarukz** [comment]
Don't try this
`
`

**Comment by jaredw42** [comment]
I couldn't get it to compile with gcc 7 but worked fine with gcc 6.

**Comment by dudash** [comment]
I was able to get it to not run on my Mac.  Can you try this?

```

```
