### ISSUE TITLE
It should not be like that. 

### ISSUE THREAD

**Issue by ZhaoDingfan** [kelseyhightower/nocode#2043]
> GitHub is supposed to be the place for developers share code and improve themselves. 

However, this repo is not likely to be any code shared for developers. Although the rank #2 repo about the experience to buy house in Hangzhou is not related to code sharing also, it is useful for Chinese people to learn more about buying house as the housing price in China is unreasonably high ;) For this repo, I don't see any useful piece of information. It is just the revenge of other developers who don't like that. 

> Hope GitHub official can take care of such condition as it is quite dangerous to let developers feel sad about GitHub. 

I am a Newbie of GitHub from China, I saw many repos before that I can learn from and I really thank for the devotion of other developers make GitHub a friendly community. However, in my opinion, **developers should focus on technology to compete for trending.**

**Comment by Ir1d** [comment]
Well, it might still be useful to someone else. "One man's meat is another man's poison".
Afaik, this repo does not violate the rules on Github.
Indeed, developers should focus on technology, but whether the repo goes on trending is not decided by the repo owner. XD.
And btw, @ZhaoDingfan you can send emails to Github support directly since this is not a valid issue.
