### ISSUE TITLE
Are the following rumours about nocode true?

### ISSUE THREAD

**Issue by tsvetann** [kelseyhightower/nocode#249]
I love your work and hope you will continue supporting it. I heard rumours that you are working on `nocode v2`. Can you shed some light please?

Thank you in advance,
NoName

**Comment by wadleo** [comment]
this is simply ingenuity, great work done here

**Comment by TheAnalogyGuy** [comment]
> I love your work and hope you will continue supporting it. I heard rumours that you are working on `nocode v2`. Can you shed some light please?
> 
> Thank you in advance, NoName

This is an old thread, but I just noticed that the new version has come out, and it actually came out shortly after your comment. The new version has many new and improved features, the primary one being that it is self-documenting. I have cloned it and been using it for a while now, and all I can say is that `     v ` works as expected and I highly recommend it. They are talking about removing the `v` in the next release, so I think it may have already been released because I found it when I looked for it.
