### ISSUE TITLE
I need help running a 0 Byte file.

### ISSUE THREAD

**Issue by NotMoni** [kelseyhightower/nocode#3918]
Never thought scaling this would be that hard.... but now its a pain in the ass.

**Comment by geary** [comment]
Scaling is one of the greatest benefits of no code, and it should be easy to implement. Just create a Kubernetes cluster with zero worker nodes.

Unfortunately you still need a Kubernetes master to orchestrate the cluster, but since it will never have to talk to a node, you can probably run it on a Raspberry Pi.

**Comment by NotMoni** [comment]
Oh.... I see. Very scaleable. I will try it out.
