### ISSUE TITLE
I can't find the document,for this beauty

### ISSUE THREAD

**Issue by TotallyJustMagic** [kelseyhightower/nocode#4289]
I searched everywhere to make this work,and work with it
But there ins't any info?
What do i do?

**Comment by cihangll** [comment]
Hi @TotallyJustMagic ,
Take a [look](#)

**Comment by Hocuri** [comment]
@TotallyJustMagic, just run:

```

```

and your problem will be magically resolved!

**Comment by TotallyJustMagic** [comment]
Thanks! That worked!

**Comment by TotallyJustMagic** [comment]
Wait i just tried to run it,and where do i run it?
i can't find that either,there ins't info on that in the documentary

**Comment by Hocuri** [comment]
Hmmm... Damn. Ok. Guys, that really puts us in a very hard situation, as in order to run it, you would need code (i.e. an operating system at least).

Maybe put it into an [unnecessary class](https://github.com/joaomilho/Enterprise#unnecessary-classes) in Enterprise? I mean, it's code, but it's unnecessary and will never be run, so it's the best solution I can come up with.

**Comment by TotallyJustMagic** [comment]
That's a good solution, but what if i don't have a operating system . I am writing this from a calculator so what can i do in that circumstances?

**Comment by Hocuri** [comment]
WAAAAH! A calculator, this means code! As the things you type in there usually are also valid code! We're doomed! Don't touch it anymore!

**Comment by Hocuri** [comment]
Throw it into Orodruin!

**Comment by Hocuri** [comment]
And wear gloves!

**Comment by Hocuri** [comment]
It will make you want to use it, but you MUST resist!

**Comment by TotallyJustMagic** [comment]
Ah anyway, i fixed the issue myself
the answer was :
not running it !
But thanks for giving me hints about it

**Comment by Hocuri** [comment]
yes, that's a very good solution.
