### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by RicoLiu** [kelseyhightower/nocode#508]
I have this error:

```javascript
```

How to fix it?

**Comment by milewski** [comment]
You need to run it with git-bash... the cmd is broken!

try

```

```

**Comment by RicoLiu** [comment]
Thx...It works for me.

**Comment by t04glovern** [comment]
Here's the PowerShell cmdlet equivalent
```
```

**Comment by yifleo** [comment]
you save my day!

**Comment by brean** [comment]
I can verify that if you to run nocode inside a cmd-file in windows 10 you get [this](http://andreasbresser.de/not_running_nocode.png) error message.
But I found a working workaround: just add a line-break to the file. I guess technically its still compatible to the no code-philosophy because it does not include any instructions...
